steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'done'
  args: ['build', '--tag=gcr.io/$PROJECT_ID/done-build', '.']

timeout: 2400s

images: ['gcr.io/$PROJECT_ID/done-build']
tags: ['done', 'build']
options:
  machineType: 'E2_HIGHCPU_32'
  defaultLogsBucketBehavior: "REGIONAL_USER_OWNED_BUCKET"
